US014: Add create action
dilmurod-rozikov/ParkingZone pull request #19
Opened 2024-04-25 12:42 UTC by dilmurod-rozikov

2024-04-25 13:22 UTC, dilmurod-rozikov commented
![](https://github.trello.services/images/mini-trello-icon.png) [-	US014 (2): Create action](https://trello.com/c/gSBYWY04/11-us014-2-create-action)

2024-04-26 15:51 UTC, dotnetdew requested changes

2024-04-26 15:51 UTC, dotnetdew commented on ParkingZoneApp.Tests/ModelValidation/ParkingSlots/CreateVMTests.cs
> +
unnecessary line

2024-04-26 15:51 UTC, dotnetdew commented on ParkingZoneApp/Services/Interfaces/IParkingSlotService.cs
> +
unnecessary line

2024-04-26 15:51 UTC, dotnetdew commented on ParkingZoneApp.Tests/Controllers/Admin/ParkingSlotControllerUnitTests.cs
> +            Category = SlotCategory.Standard,
Where are the tests for Create action????

2024-04-29 03:24 UTC, dotnetdew requested changes

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Controllers/Admin/ParkingSlotControllerUnitTests.cs
> +        #region
where is the region name?

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Controllers/Admin/ParkingSlotControllerUnitTests.cs
> +            var result = _controller.Create(createVM);
```suggestion
            var result = _controller.Create(id);
```

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Controllers/Admin/ParkingSlotControllerUnitTests.cs
> +            var result = _controller.Create(createVM);
you said given id but you gave create VM

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Controllers/Admin/ParkingSlotControllerUnitTests.cs
> +            CreateVM createVM = new CreateVM()
```suggestion
            CreateVM expectedCreateVM = new CreateVM()
```

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Controllers/Admin/ParkingSlotControllerUnitTests.cs
> +        }
Json serializer

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Controllers/Admin/ParkingSlotControllerUnitTests.cs
> +        public void GivenParkingSlotId_WhenCreatePostIsCalled_ThenReturnModelErrorIfNumberIsNotUnique()
```suggestion
        public void GivenCreateVM_WhenCreatePostIsCalled_ThenReturnModelErrorIfNumberIsNotUnique()
```

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Controllers/Admin/ParkingSlotControllerUnitTests.cs
> +        public void GivenParkingSlotId_WhenCreatePostIsCalled_ThenReturnModelErrorIfNumberIsNotUnique()
here below you gave create VM

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Services/ParkingSlotServiceTests.cs
> +        public void GivenIdAndNumber_WhenIsUniqueNumberIsCalled_ThenReturnTrueIfNumberIsUnique()
```suggestion
        public void GivenIdAndNumber_WhenIsUniqueNumberIsCalled_ThenReturnsTrue()
```

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Services/ParkingSlotServiceTests.cs
> +            Assert.True(!result);
```suggestion
            Assert.True(result);
```

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Services/ParkingSlotServiceTests.cs
> +            Assert.True(!result);
here i suppose result was false and you added ! to make it True :)

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Services/ParkingSlotServiceTests.cs
> +        public void GivenIdAndNumber_WhenIsUniqueNumberIsCalled_ThenReturnFalseIfNumberIsUnique()
```suggestion
        public void GivenIdAndNumber_WhenIsUniqueNumberIsCalled_ThenReturnsFalse()
```

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Services/ParkingSlotServiceTests.cs
> +            Assert.False(!result);
```suggestion
            Assert.False(result);
```

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp.Tests/Services/ParkingSlotServiceTests.cs
> +            Assert.False(!result);
here you should not change the result with !

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Controllers/ParkingSlotController.cs
> +            var sorted = listItemVMs.OrderBy(item => item.Number);
there is no need to make them sorted because we have such kind of task further (filtering)

2024-04-29 03:24 UTC, dotnetdew commented on ParkingZoneApp/Areas/Admin/Views/ParkingSlot/Index.cshtml
> +                <h6>Number</h6>
this way is called "dehqoncha", lets make it in a MVC way with HTML.displayfor() or other

2024-04-29 10:40 UTC, dotnetdew approved these changes

2024-04-29 12:09 UTC, merged