US022: Add prolong action for active reservations
dilmurod-rozikov/ParkingZone pull request #27
Opened 2024-05-16 17:09 UTC by dilmurod-rozikov

2024-05-16 19:33 UTC, SamDotNetDev approved these changes

2024-05-17 14:43 UTC, dotnetdew requested changes

2024-05-17 14:43 UTC, dotnetdew commented on ParkingZoneApp/Services/ReservationService.cs
> +        public IEnumerable<Reservation> GetReservationsByUser(string userId)
```suggestion
        public IEnumerable<Reservation> GetReservationsByUserId(string userId)
```

2024-05-17 14:43 UTC, dotnetdew commented on ParkingZoneApp/Services/Interfaces/IReservationService.cs
> +        public IEnumerable<Reservation> GetReservationsByUser(string userId);
```suggestion
        public IEnumerable<Reservation> GetReservationsByUserId(string userId);
```

2024-05-17 14:43 UTC, dotnetdew commented on ParkingZoneApp/Views/Reservation/FreeSlots.cshtml
> +    <table class="table table-success table-striped table-hover">
space

2024-05-17 15:12 UTC, dotnetdew approved these changes

2024-05-17 15:15 UTC, merged