US023: apply - slot cannot be modified if it is in use
dilmurod-rozikov/ParkingZone pull request #28
Opened 2024-05-18 04:49 UTC by dilmurod-rozikov

2024-05-18 09:43 UTC, SamDotNetDev requested changes

2024-05-18 09:43 UTC, SamDotNetDev commented on ParkingZoneApp.Tests/Controllers/Admin/ParkingSlotControllerUnitTests.cs
> +        public void GivenEditVMAndParkingSlotId_WhenEditPostIsCalled_ThenReturnModelErrorIfNumberIsNotUnique()
```suggestion
        public void GivenEditVMAndParkingSlotId_WhenEditPostIsCalled_ThenNumberIsNotUniqueAndModelStateIsFalseAndReturnsViewResult()
```

2024-05-18 09:43 UTC, SamDotNetDev commented on ParkingZoneApp.Tests/Controllers/Admin/ParkingSlotControllerUnitTests.cs
> +        public void GivenEditVMAndParkingSlotId_WhenEditPostIsCalled_ThenReturnModelErrorIfSlotIsInUse()
why return it is grammatically wrong i think lets do like this 
```suggestion
        public void GivenEditVMAndParkingSlotId_WhenEditPostIsCalled_ThenSlotIsInUseAndModelStateIsFalseAndReturnsViewResult()
```

2024-05-18 09:45 UTC, SamDotNetDev approved these changes

2024-05-18 09:56 UTC, dilmurod-rozikov commented
![](https://github.trello.services/images/mini-trello-icon.png) [-	US023 (1): Modify slot editing action. Slot category cannot be modified if it is in use. In this case make this field readonly and show corresponding warning message near it. Also check on POST if a slot is in use.](https://trello.com/c/NFyV3I7S/19-us023-1-modify-slot-editing-action-slot-category-cannot-be-modified-if-it-is-in-use-in-this-case-make-this-field-readonly-and-s)

2024-05-20 04:39 UTC, dotnetdew requested changes

2024-05-20 04:39 UTC, dotnetdew commented on ParkingZoneApp/Models/Entities/ParkingSlot.cs
> +        public bool IsSlotInUse
```suggestion
        public bool IsInUse
```

2024-05-20 04:39 UTC, dotnetdew commented on ParkingZoneApp/Models/Entities/ParkingSlot.cs
> +        public bool IsSlotInUse
we dont need word "Slot" because its staying in model called "Slot"

2024-05-20 10:37 UTC, abdullokhtolibjonov approved these changes

2024-05-20 10:47 UTC, merged