US027: Apply get current cars action
dilmurod-rozikov/ParkingZone pull request #33
Opened 2024-05-24 17:39 UTC by dilmurod-rozikov

2024-05-24 17:59 UTC, SamDotNetDev requested changes

2024-05-24 17:59 UTC, SamDotNetDev commented on ParkingZoneApp.Tests/ModelValidation/ParkingSlots/FilterSlotVMTests.cs
> +        public void GivenItemToBeValidated_WhenCreatingGetCurrentCarsVM_ThenValidationIsPerformed
```suggestion
        public void GivenItemToBeValidated_WhenCreatingFilterSlotsVM_ThenValidationIsPerformed
```

2024-05-24 17:59 UTC, SamDotNetDev commented on ParkingZoneApp.Tests/ModelValidation/ParkingZones/GetCurrentCarsTests.cs
> +                new object[] { 1, "Test1", true },
check for null also for VehicleNumber cuz string could be null

2024-05-24 17:59 UTC, SamDotNetDev commented on ParkingZoneApp/Services/ReservationService.cs
> +            return GetAll().Where(x => x.ParkingZoneId == zoneId);
logic is wrong you have to show current cars not all. Now you are showing even the cars which were in the parkingZone in the past. You have to take only cars which are currently in certain ParkingZone

2024-05-25 04:21 UTC, dilmurod-rozikov commented on ParkingZoneApp.Tests/ModelValidation/ParkingZones/GetCurrentCarsTests.cs
> +                new object[] { 1, "Test1", true },
I did and it is failing for no reason

2024-05-25 08:56 UTC, SamDotNetDev commented on ParkingZoneApp.Tests/ModelValidation/ParkingZones/GetCurrentCarsTests.cs
> +                new object[] { 1, "Test1", true },
try to solve it it has to check for null also

2024-05-25 08:58 UTC, SamDotNetDev approved these changes

2024-05-28 05:30 UTC, dotnetdew approved these changes

2024-05-28 09:49 UTC, merged